#!/usr/bin/env bash
#
# Regenerate the ARCHITECTURE.md files in `examples/` by cloning a curated
# set of popular OSS JS/TS projects into a temp directory, running the
# locally-built zinsight against each, and copying the output into the
# repo under `examples/<project>/ARCHITECTURE.md`.
#
# Re-run any time after meaningful zinsight changes:
#
#     ./scripts/generate-examples.sh
#
# Requires: git, node, npm. No network calls beyond `git clone --depth=1`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXAMPLES_DIR="${REPO_ROOT}/examples"
TMP_DIR="$(mktemp -d)"
trap "rm -rf ${TMP_DIR}" EXIT

# Make sure dist is built before we run zinsight against the targets.
echo "🔨 Building zinsight..."
( cd "${REPO_ROOT}" && npm run --silent build )
ZINSIGHT="${REPO_ROOT}/dist/cli/index.js"

# Curated list — picked for variety: classic Express, modern Fastify,
# decorator-heavy NestJS, edge-runtime Hono. All popular, all well-known
# enough that "zinsight on <project>" is tweetable.
#
# Format: "<slug>|<git-url>|<sub-path>"
TARGETS=(
  "nestjs|https://github.com/nestjs/nest.git|packages/core"
  "fastify|https://github.com/fastify/fastify.git|."
  "hono|https://github.com/honojs/hono.git|src"
  "expressjs|https://github.com/expressjs/express.git|."
)

mkdir -p "${EXAMPLES_DIR}"

for target in "${TARGETS[@]}"; do
  IFS='|' read -r slug url subpath <<< "${target}"
  out_dir="${EXAMPLES_DIR}/${slug}"
  out_file="${out_dir}/ARCHITECTURE.md"
  mkdir -p "${out_dir}"

  echo ""
  echo "📥 Cloning ${slug} from ${url}"
  clone_dir="${TMP_DIR}/${slug}"
  git clone --depth=1 --quiet "${url}" "${clone_dir}" >/dev/null

  analyse_dir="${clone_dir}/${subpath}"
  echo "🔍 Running zinsight on ${analyse_dir}"
  if ! node "${ZINSIGHT}" --root "${analyse_dir}" --output "${out_file}" >/dev/null 2>&1; then
    echo "  ⚠️  zinsight failed for ${slug} — skipping."
    continue
  fi

  # Replace the auto-generated date line so re-runs aren't noisy in git
  # diffs purely because the timestamp moved.
  if [ -f "${out_file}" ]; then
    sed -i.bak -E "s/Auto-generated by \[zinsight\]\([^)]*\) on [0-9-]+/Auto-generated by [zinsight](https:\/\/github.com\/zinboard\/zinsight) on YYYY-MM-DD/" "${out_file}"
    rm -f "${out_file}.bak"
    lines=$(wc -l < "${out_file}" | tr -d ' ')
    bytes=$(wc -c < "${out_file}" | tr -d ' ')
    echo "  ✅ ${out_file} (${lines} lines, ${bytes} bytes)"
  fi
done

echo ""
echo "✨ All examples regenerated. Commit changes under ${EXAMPLES_DIR}/"
